[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840_xxAA"

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "info"
BINDGEN_EXTRA_CLANG_ARGS = "--target=arm-none-eabi --sysroot=/usr/arm-none-eabi"

[target.thumbv7em-none-eabihf]
rustflags = ['--cfg', 'getrandom_backend="custom"']
